blank_issues_enabled: false
contact_links:
  - name: MoreLoad Discord
    url: https://dyonic.me/discord
    about: Ask for help with anything related to MoreLoad!
  - name: MoreLoad Docs
    url: https://moreload.com
    about: Maybe take a look a the docs?
